---
engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  csslint:
    enabled: true
    checks:
      net.csslint.DisallowIDsinselectors:
        enabled: false
      net.csslint.Disallowadjoiningclasses:
        enabled: false
      net.csslint.Requirecompatiblevendorprefixes:
        enabled: false
      net.csslint.Disallowuseofbox-sizing:
        enabled: false
  fixme:
    enabled: false
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths:
- node_modules/**/*
- source/firefox/bootstrap.js
