---
engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: false
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths:
- node_modules/**/*
- source/firefox/bootstrap.js
